import AppContainer from '@/components/layout/appContainer';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Sen } from 'next/font/google';
import './globals.css';

const sen = Sen({
	variable: '--font-geist-sen',
	subsets: ['latin'],
});

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} bg-background ${sen.variable} ${geistMono.variable} antialiased`}
			>
				<AppContainer>{children}</AppContainer>
			</body>
		</html>
	);
}
